name: learn_google_map
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.4+1
  http: ^1.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  polymaker: ^1.0.3
  geolocator: ^9.0.0
  flutter_compass: ^0.7.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  assets:
    - assets/location.json
 
